services:
    database:
        image: postgres:latest
        container_name: shop_postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /data/postgres
            POSTGRES_DB: bank
        volumes:
            - db:/data/postgres
        ports:
            - "5332:5432"
        networks:
            - main
        restart: unless-stopped
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -d postgres" ]
            interval: 30s
            timeout: 10s
            retries: 5
    admin:
        container_name: shop_adminer
        image: adminer:latest
        restart: always
        depends_on:
            - database
        ports:
            - 8080:8080
        networks:
            - main
networks:
    main:
        driver: bridge
volumes:
    db:
