/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

const metadata = {
    models: {
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, email: {
                    name: "email",
                    type: "String",
                }, username: {
                    name: "username",
                    type: "String",
                }, password: {
                    name: "password",
                    type: "String",
                }, name: {
                    name: "name",
                    type: "String",
                }, phone: {
                    name: "phone",
                    type: "String",
                    isOptional: true,
                }, addresses: {
                    name: "addresses",
                    type: "Address",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, birthday: {
                    name: "birthday",
                    type: "DateTime",
                    isOptional: true,
                }, isEnabled: {
                    name: "isEnabled",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": true }] }],
                }, role: {
                    name: "role",
                    type: "Role",
                    attributes: [{ "name": "@default", "args": [] }],
                }, profileImage: {
                    name: "profileImage",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, lastLoginAt: {
                    name: "lastLoginAt",
                    type: "DateTime",
                    isOptional: true,
                }, carts: {
                    name: "carts",
                    type: "Cart",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, orders: {
                    name: "orders",
                    type: "Order",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, deliveries: {
                    name: "deliveries",
                    type: "Delivery",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'driver',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                }, username: {
                    name: "username",
                    fields: ["username"]
                },
            }
            ,
        }
        ,
        address: {
            name: 'Address', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, userId: {
                    name: "userId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'user',
                }, label: {
                    name: "label",
                    type: "String",
                }, streetAddress: {
                    name: "streetAddress",
                    type: "String",
                }, city: {
                    name: "city",
                    type: "String",
                }, state: {
                    name: "state",
                    type: "String",
                    isOptional: true,
                }, postalCode: {
                    name: "postalCode",
                    type: "String",
                }, country: {
                    name: "country",
                    type: "String",
                }, isDefault: {
                    name: "isDefault",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": false }] }],
                }, phoneNumber: {
                    name: "phoneNumber",
                    type: "String",
                    isOptional: true,
                }, deliveryNotes: {
                    name: "deliveryNotes",
                    type: "String",
                    isOptional: true,
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'addresses',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, deliveryFrom: {
                    name: "deliveryFrom",
                    type: "Delivery",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'fromAddress',
                }, deliveryTo: {
                    name: "deliveryTo",
                    type: "Delivery",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'toAddress',
                }, orders: {
                    name: "orders",
                    type: "Order",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'address',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        category: {
            name: 'Category', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, slug: {
                    name: "slug",
                    type: "String",
                }, parentId: {
                    name: "parentId",
                    type: "Int",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'parent',
                }, isActive: {
                    name: "isActive",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": true }] }],
                }, parent: {
                    name: "parent",
                    type: "Category",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'subCategories',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "parentId" },
                }, subCategories: {
                    name: "subCategories",
                    type: "Category",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'parent',
                }, product: {
                    name: "product",
                    type: "Product",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'category',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                }, slug: {
                    name: "slug",
                    fields: ["slug"]
                },
            }
            ,
        }
        ,
        product: {
            name: 'Product', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, slug: {
                    name: "slug",
                    type: "String",
                }, quantity: {
                    name: "quantity",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "value": 0 }] }],
                }, brand: {
                    name: "brand",
                    type: "String",
                    isOptional: true,
                }, categoryId: {
                    name: "categoryId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'category',
                }, status: {
                    name: "status",
                    type: "ProductStatus",
                    attributes: [{ "name": "@default", "args": [] }],
                }, type: {
                    name: "type",
                    type: "String",
                    isOptional: true,
                }, weight: {
                    name: "weight",
                    type: "Decimal",
                    isOptional: true,
                }, dimensions: {
                    name: "dimensions",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, variants: {
                    name: "variants",
                    type: "ProductVariant",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'product',
                }, carts: {
                    name: "carts",
                    type: "Cart",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'product',
                }, orderItems: {
                    name: "orderItems",
                    type: "OrderItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'product',
                }, category: {
                    name: "category",
                    type: "Category",
                    isDataModel: true,
                    backLink: 'product',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "categoryId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, slug: {
                    name: "slug",
                    fields: ["slug"]
                },
            }
            ,
        }
        ,
        attribute: {
            name: 'Attribute', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, name: {
                    name: "name",
                    type: "String",
                }, displayName: {
                    name: "displayName",
                    type: "String",
                }, values: {
                    name: "values",
                    type: "AttributeValue",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'attribute',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                },
            }
            ,
        }
        ,
        attributeValue: {
            name: 'AttributeValue', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, attributeId: {
                    name: "attributeId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'attribute',
                }, value: {
                    name: "value",
                    type: "String",
                }, attribute: {
                    name: "attribute",
                    type: "Attribute",
                    isDataModel: true,
                    backLink: 'values',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "attributeId" },
                }, variantOptions: {
                    name: "variantOptions",
                    type: "VariantOption",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'attributeValue',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, attributeId_value: {
                    name: "attributeId_value",
                    fields: ["attributeId", "value"]
                },
            }
            ,
        }
        ,
        productVariant: {
            name: 'ProductVariant', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, productId: {
                    name: "productId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'product',
                }, sku: {
                    name: "sku",
                    type: "String",
                }, price: {
                    name: "price",
                    type: "Decimal",
                }, salePrice: {
                    name: "salePrice",
                    type: "Decimal",
                    isOptional: true,
                }, quantity: {
                    name: "quantity",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "value": 0 }] }],
                }, image: {
                    name: "image",
                    type: "String",
                    isOptional: true,
                }, product: {
                    name: "product",
                    type: "Product",
                    isDataModel: true,
                    backLink: 'variants',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "productId" },
                }, options: {
                    name: "options",
                    type: "VariantOption",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'variant',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, sku: {
                    name: "sku",
                    fields: ["sku"]
                },
            }
            ,
        }
        ,
        variantOption: {
            name: 'VariantOption', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, variantId: {
                    name: "variantId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'variant',
                }, attributeValueId: {
                    name: "attributeValueId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'attributeValue',
                }, variant: {
                    name: "variant",
                    type: "ProductVariant",
                    isDataModel: true,
                    backLink: 'options',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "variantId" },
                }, attributeValue: {
                    name: "attributeValue",
                    type: "AttributeValue",
                    isDataModel: true,
                    backLink: 'variantOptions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "attributeValueId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, variantId_attributeValueId: {
                    name: "variantId_attributeValueId",
                    fields: ["variantId", "attributeValueId"]
                },
            }
            ,
        }
        ,
        cart: {
            name: 'Cart', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, userId: {
                    name: "userId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'user',
                }, productId: {
                    name: "productId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'product',
                }, variantId: {
                    name: "variantId",
                    type: "Int",
                    isOptional: true,
                }, quantity: {
                    name: "quantity",
                    type: "Int",
                }, addedAt: {
                    name: "addedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'carts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, product: {
                    name: "product",
                    type: "Product",
                    isDataModel: true,
                    backLink: 'carts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "productId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, userId_productId_variantId: {
                    name: "userId_productId_variantId",
                    fields: ["userId", "productId", "variantId"]
                },
            }
            ,
        }
        ,
        order: {
            name: 'Order', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, orderCode: {
                    name: "orderCode",
                    type: "String",
                }, userId: {
                    name: "userId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'user',
                }, addressId: {
                    name: "addressId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'address',
                }, totalAmount: {
                    name: "totalAmount",
                    type: "Decimal",
                }, subtotal: {
                    name: "subtotal",
                    type: "Decimal",
                }, taxAmount: {
                    name: "taxAmount",
                    type: "Decimal",
                }, shippingAmount: {
                    name: "shippingAmount",
                    type: "Decimal",
                }, discountAmount: {
                    name: "discountAmount",
                    type: "Decimal",
                    attributes: [{ "name": "@default", "args": [{ "value": 0 }] }],
                }, couponCode: {
                    name: "couponCode",
                    type: "String",
                    isOptional: true,
                }, orderDate: {
                    name: "orderDate",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, status: {
                    name: "status",
                    type: "OrderStatus",
                    attributes: [{ "name": "@default", "args": [] }],
                }, paymentStatus: {
                    name: "paymentStatus",
                    type: "PaymentStatus",
                    attributes: [{ "name": "@default", "args": [] }],
                }, paymentMethod: {
                    name: "paymentMethod",
                    type: "String",
                }, paymentId: {
                    name: "paymentId",
                    type: "String",
                    isOptional: true,
                }, notes: {
                    name: "notes",
                    type: "String",
                    isOptional: true,
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'orders',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, address: {
                    name: "address",
                    type: "Address",
                    isDataModel: true,
                    backLink: 'orders',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "addressId" },
                }, orderItems: {
                    name: "orderItems",
                    type: "OrderItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'order',
                }, statusHistory: {
                    name: "statusHistory",
                    type: "OrderStatusHistory",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'order',
                }, deliveries: {
                    name: "deliveries",
                    type: "Delivery",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'order',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, orderCode: {
                    name: "orderCode",
                    fields: ["orderCode"]
                },
            }
            ,
        }
        ,
        orderItem: {
            name: 'OrderItem', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, orderId: {
                    name: "orderId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'order',
                }, productId: {
                    name: "productId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'product',
                }, quantity: {
                    name: "quantity",
                    type: "Int",
                }, unitPrice: {
                    name: "unitPrice",
                    type: "Decimal",
                }, totalPrice: {
                    name: "totalPrice",
                    type: "Decimal",
                }, discount: {
                    name: "discount",
                    type: "Decimal",
                    attributes: [{ "name": "@default", "args": [{ "value": 0 }] }],
                }, productName: {
                    name: "productName",
                    type: "String",
                }, productSku: {
                    name: "productSku",
                    type: "String",
                }, variantOptions: {
                    name: "variantOptions",
                    type: "String",
                    isOptional: true,
                }, order: {
                    name: "order",
                    type: "Order",
                    isDataModel: true,
                    backLink: 'orderItems',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderId" },
                }, product: {
                    name: "product",
                    type: "Product",
                    isDataModel: true,
                    backLink: 'orderItems',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "productId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        orderStatusHistory: {
            name: 'OrderStatusHistory', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, orderId: {
                    name: "orderId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'order',
                }, status: {
                    name: "status",
                    type: "OrderStatus",
                }, notes: {
                    name: "notes",
                    type: "String",
                    isOptional: true,
                }, createdById: {
                    name: "createdById",
                    type: "Int",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, order: {
                    name: "order",
                    type: "Order",
                    isDataModel: true,
                    backLink: 'statusHistory',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        delivery: {
            name: 'Delivery', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, orderId: {
                    name: "orderId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'order',
                }, driverId: {
                    name: "driverId",
                    type: "Int",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'driver',
                }, fromAddressId: {
                    name: "fromAddressId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'fromAddress',
                }, toAddressId: {
                    name: "toAddressId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'toAddress',
                }, scheduledDate: {
                    name: "scheduledDate",
                    type: "DateTime",
                    isOptional: true,
                }, deliveredDate: {
                    name: "deliveredDate",
                    type: "DateTime",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "DeliveryStatus",
                    attributes: [{ "name": "@default", "args": [] }],
                }, estimatedDelivery: {
                    name: "estimatedDelivery",
                    type: "DateTime",
                    isOptional: true,
                }, notes: {
                    name: "notes",
                    type: "String",
                    isOptional: true,
                }, order: {
                    name: "order",
                    type: "Order",
                    isDataModel: true,
                    backLink: 'deliveries',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderId" },
                }, driver: {
                    name: "driver",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'deliveries',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "driverId" },
                }, fromAddress: {
                    name: "fromAddress",
                    type: "Address",
                    isDataModel: true,
                    backLink: 'deliveryFrom',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "fromAddressId" },
                }, toAddress: {
                    name: "toAddress",
                    type: "Address",
                    isDataModel: true,
                    backLink: 'deliveryTo',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "toAddressId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
    }
    ,
    deleteCascade: {
        user: ['Address', 'Cart'],
        product: ['ProductVariant', 'Cart'],
        attribute: ['AttributeValue'],
        attributeValue: ['VariantOption'],
        productVariant: ['VariantOption'],
        order: ['OrderItem', 'OrderStatusHistory'],
    }
    ,
    authModel: 'User'
};
export default metadata;
