server:
    port: 8092
    servlet:
        context-path: /api

spring:
    datasource:
        hikari:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/shoppee?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
            username: root
            password:
            connectionTimeout: 30000
            idleTimeout: 600000
            maxLifetime: 1800000
            minimumIdle: 2
            maximumPoolSize: 10
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        hibernate:
            ddl-auto: update
app:
    jwt:
        secret: y2V7wAhnzZ1cQexXkbFkGdLuY1pK2Nuy
        expiration: 2592000000
logging:
    config: file:${workdir:.}/config/logback.xml
