/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

const metadata = {
    models: {
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "BigInt",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, email: {
                    name: "email",
                    type: "String",
                }, password: {
                    name: "password",
                    type: "String",
                }, name: {
                    name: "name",
                    type: "String",
                }, phone: {
                    name: "phone",
                    type: "String",
                    isOptional: true,
                }, address: {
                    name: "address",
                    type: "String",
                    isOptional: true,
                }, birthday: {
                    name: "birthday",
                    type: "DateTime",
                    isOptional: true,
                }, isEnabled: {
                    name: "isEnabled",
                    type: "Int",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [{ "value": 1 }] }],
                }, roleId: {
                    name: "roleId",
                    type: "Int",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [{ "value": 2 }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    isOptional: true,
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, orders: {
                    name: "orders",
                    type: "Order",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, carts: {
                    name: "carts",
                    type: "Cart",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                },
            }
            ,
        }
        ,
        product: {
            name: 'Product', fields: {
                id: {
                    name: "id",
                    type: "BigInt",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, price: {
                    name: "price",
                    type: "Decimal",
                }, salePrice: {
                    name: "salePrice",
                    type: "Decimal",
                    isOptional: true,
                }, quantity: {
                    name: "quantity",
                    type: "BigInt",
                }, brand: {
                    name: "brand",
                    type: "String",
                    isOptional: true,
                }, type: {
                    name: "type",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'category',
                }, image: {
                    name: "image",
                    type: "String",
                    isOptional: true,
                }, thumbnail: {
                    name: "thumbnail",
                    type: "String",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "value": 1 }] }],
                }, productView: {
                    name: "productView",
                    type: "BigInt",
                    attributes: [{ "name": "@default", "args": [{ "value": 0 }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    isOptional: true,
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, screenSize: {
                    name: "screenSize",
                    type: "String",
                    isOptional: true,
                }, screenResolution: {
                    name: "screenResolution",
                    type: "String",
                    isOptional: true,
                }, operatingSystem: {
                    name: "operatingSystem",
                    type: "String",
                    isOptional: true,
                }, cpu: {
                    name: "cpu",
                    type: "String",
                    isOptional: true,
                }, ram: {
                    name: "ram",
                    type: "String",
                    isOptional: true,
                }, storage: {
                    name: "storage",
                    type: "String",
                    isOptional: true,
                }, battery: {
                    name: "battery",
                    type: "String",
                    isOptional: true,
                }, weight: {
                    name: "weight",
                    type: "String",
                    isOptional: true,
                }, category: {
                    name: "category",
                    type: "Category",
                    isDataModel: true,
                    backLink: 'products',
                    isRelationOwner: true,
                    foreignKeyMapping: { "code": "type" },
                }, orderDetails: {
                    name: "orderDetails",
                    type: "OrderDetail",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'product',
                }, carts: {
                    name: "carts",
                    type: "Cart",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'product',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        category: {
            name: 'Category', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, code: {
                    name: "code",
                    type: "String",
                }, name: {
                    name: "name",
                    type: "String",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    isOptional: true,
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, products: {
                    name: "products",
                    type: "Product",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'category',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, code: {
                    name: "code",
                    fields: ["code"]
                },
            }
            ,
        }
        ,
        cart: {
            name: 'Cart', fields: {
                id: {
                    name: "id",
                    type: "BigInt",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, userId: {
                    name: "userId",
                    type: "BigInt",
                    isForeignKey: true,
                    relationField: 'user',
                }, productId: {
                    name: "productId",
                    type: "BigInt",
                    isForeignKey: true,
                    relationField: 'product',
                }, quantity: {
                    name: "quantity",
                    type: "BigInt",
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'carts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, product: {
                    name: "product",
                    type: "Product",
                    isDataModel: true,
                    backLink: 'carts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "productId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        order: {
            name: 'Order', fields: {
                id: {
                    name: "id",
                    type: "BigInt",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, orderCode: {
                    name: "orderCode",
                    type: "String",
                }, nameOrder: {
                    name: "nameOrder",
                    type: "String",
                }, phoneNumber: {
                    name: "phoneNumber",
                    type: "String",
                }, address: {
                    name: "address",
                    type: "String",
                }, notes: {
                    name: "notes",
                    type: "String",
                    isOptional: true,
                }, orderDate: {
                    name: "orderDate",
                    type: "DateTime",
                }, deliveryDate: {
                    name: "deliveryDate",
                    type: "DateTime",
                    isOptional: true,
                }, orderStatus: {
                    name: "orderStatus",
                    type: "String",
                }, totalAmount: {
                    name: "totalAmount",
                    type: "Decimal",
                }, userId: {
                    name: "userId",
                    type: "BigInt",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'orders',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, orderDetails: {
                    name: "orderDetails",
                    type: "OrderDetail",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'order',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        orderDetail: {
            name: 'OrderDetail', fields: {
                id: {
                    name: "id",
                    type: "BigInt",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    isAutoIncrement: true,
                }, orderId: {
                    name: "orderId",
                    type: "BigInt",
                    isForeignKey: true,
                    relationField: 'order',
                }, productId: {
                    name: "productId",
                    type: "BigInt",
                    isForeignKey: true,
                    relationField: 'product',
                }, quantity: {
                    name: "quantity",
                    type: "BigInt",
                }, unitPrice: {
                    name: "unitPrice",
                    type: "Decimal",
                }, order: {
                    name: "order",
                    type: "Order",
                    isDataModel: true,
                    backLink: 'orderDetails',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderId" },
                }, product: {
                    name: "product",
                    type: "Product",
                    isDataModel: true,
                    backLink: 'orderDetails',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "productId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
    }
    ,
    deleteCascade: {
        user: ['Cart'],
        product: ['Cart'],
        order: ['OrderDetail'],
    }
    ,
    authModel: 'User'
};
export default metadata;
